//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHelper.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to ASUS ACPI. Application can&apos;t function without it. Try to install Asus System Control Interface.
        /// </summary>
        public static string ACPIError {
            get {
                return ResourceManager.GetString("ACPIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart your device to apply changes.
        /// </summary>
        public static string AlertAPUMemoryRestart {
            get {
                return ResourceManager.GetString("AlertAPUMemoryRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart now?.
        /// </summary>
        public static string AlertAPUMemoryRestartTitle {
            get {
                return ResourceManager.GetString("AlertAPUMemoryRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like GPU is in heavy use, disable it?.
        /// </summary>
        public static string AlertDGPU {
            get {
                return ResourceManager.GetString("AlertDGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco Mode.
        /// </summary>
        public static string AlertDGPUTitle {
            get {
                return ResourceManager.GetString("AlertDGPUTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching off Ultimate Mode requires restart.
        /// </summary>
        public static string AlertUltimateOff {
            get {
                return ResourceManager.GetString("AlertUltimateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate Mode requires restart.
        /// </summary>
        public static string AlertUltimateOn {
            get {
                return ResourceManager.GetString("AlertUltimateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot now?.
        /// </summary>
        public static string AlertUltimateTitle {
            get {
                return ResourceManager.GetString("AlertUltimateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ally Controller.
        /// </summary>
        public static string AllyController {
            get {
                return ResourceManager.GetString("AllyController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient mode may increase resource usage.
        /// </summary>
        public static string AmbientModeResources {
            get {
                return ResourceManager.GetString("AmbientModeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Speed.
        /// </summary>
        public static string AnimationSpeed {
            get {
                return ResourceManager.GetString("AnimationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime Matrix.
        /// </summary>
        public static string AnimeMatrix {
            get {
                return ResourceManager.GetString("AnimeMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App already running.
        /// </summary>
        public static string AppAlreadyRunning {
            get {
                return ResourceManager.GetString("AppAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-Helper is already running. Check system tray for an icon..
        /// </summary>
        public static string AppAlreadyRunningText {
            get {
                return ResourceManager.GetString("AppAlreadyRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Custom Fan Curve.
        /// </summary>
        public static string ApplyFanCurve {
            get {
                return ResourceManager.GetString("ApplyFanCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Power Limits.
        /// </summary>
        public static string ApplyPowerLimits {
            get {
                return ResourceManager.GetString("ApplyPowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto adjust Windows Power Modes.
        /// </summary>
        public static string ApplyWindowsPowerPlan {
            get {
                return ResourceManager.GetString("ApplyWindowsPowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Assigned to GPU.
        /// </summary>
        public static string APUMemory {
            get {
                return ResourceManager.GetString("APUMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asus Services Running.
        /// </summary>
        public static string AsusServicesRunning {
            get {
                return ResourceManager.GetString("AsusServicesRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery State.
        /// </summary>
        public static string AuraBatteryState {
            get {
                return ResourceManager.GetString("AuraBatteryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breathe.
        /// </summary>
        public static string AuraBreathe {
            get {
                return ResourceManager.GetString("AuraBreathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        public static string AuraClockwise {
            get {
                return ResourceManager.GetString("AuraClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Cycle.
        /// </summary>
        public static string AuraColorCycle {
            get {
                return ResourceManager.GetString("AuraColorCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comet.
        /// </summary>
        public static string AuraComet {
            get {
                return ResourceManager.GetString("AuraComet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterclockwise.
        /// </summary>
        public static string AuraCounterClockwise {
            get {
                return ResourceManager.GetString("AuraCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string AuraFast {
            get {
                return ResourceManager.GetString("AuraFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting Mode.
        /// </summary>
        public static string AuraLightingMode {
            get {
                return ResourceManager.GetString("AuraLightingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string AuraNormal {
            get {
                return ResourceManager.GetString("AuraNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        public static string AuraRainbow {
            get {
                return ResourceManager.GetString("AuraRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string AuraRandomColor {
            get {
                return ResourceManager.GetString("AuraRandomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to React.
        /// </summary>
        public static string AuraReact {
            get {
                return ResourceManager.GetString("AuraReact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string AuraSlow {
            get {
                return ResourceManager.GetString("AuraSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string AuraStatic {
            get {
                return ResourceManager.GetString("AuraStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobe.
        /// </summary>
        public static string AuraStrobe {
            get {
                return ResourceManager.GetString("AuraStrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AuraZoneAll {
            get {
                return ResourceManager.GetString("AuraZoneAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string AuraZoneDock {
            get {
                return ResourceManager.GetString("AuraZoneDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string AuraZoneLogo {
            get {
                return ResourceManager.GetString("AuraZoneLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrollwheel.
        /// </summary>
        public static string AuraZoneScroll {
            get {
                return ResourceManager.GetString("AuraZoneScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underglow.
        /// </summary>
        public static string AuraZoneUnderglow {
            get {
                return ResourceManager.GetString("AuraZoneUnderglow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Apply.
        /// </summary>
        public static string AutoApply {
            get {
                return ResourceManager.GetString("AutoApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets 60Hz to save battery, and back when plugged.
        /// </summary>
        public static string AutoRefreshTooltip {
            get {
                return ResourceManager.GetString("AutoRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awake.
        /// </summary>
        public static string Awake {
            get {
                return ResourceManager.GetString("Awake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string BacklightLow {
            get {
                return ResourceManager.GetString("BacklightLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string BacklightMax {
            get {
                return ResourceManager.GetString("BacklightMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid.
        /// </summary>
        public static string BacklightMid {
            get {
                return ResourceManager.GetString("BacklightMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string BacklightOff {
            get {
                return ResourceManager.GetString("BacklightOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout plugged / on battery (0 - ON).
        /// </summary>
        public static string BacklightTimeout {
            get {
                return ResourceManager.GetString("BacklightTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlight Timeout when on battery.
        /// </summary>
        public static string BacklightTimeoutBattery {
            get {
                return ResourceManager.GetString("BacklightTimeoutBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlight Timeout when plugged.
        /// </summary>
        public static string BacklightTimeoutPlugged {
            get {
                return ResourceManager.GetString("BacklightTimeoutPlugged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        public static string Balanced {
            get {
                return ResourceManager.GetString("Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string BatteryCharge {
            get {
                return ResourceManager.GetString("BatteryCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Charge Limit.
        /// </summary>
        public static string BatteryChargeLimit {
            get {
                return ResourceManager.GetString("BatteryChargeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Health.
        /// </summary>
        public static string BatteryHealth {
            get {
                return ResourceManager.GetString("BatteryHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time charge to 100%.
        /// </summary>
        public static string BatteryLimitFull {
            get {
                return ResourceManager.GetString("BatteryLimitFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding.
        /// </summary>
        public static string Binding {
            get {
                return ResourceManager.GetString("Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string BindingPrimary {
            get {
                return ResourceManager.GetString("BindingPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string BindingSecondary {
            get {
                return ResourceManager.GetString("BindingSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIOS and Driver Updates.
        /// </summary>
        public static string BiosAndDriverUpdates {
            get {
                return ResourceManager.GetString("BiosAndDriverUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot.
        /// </summary>
        public static string Boot {
            get {
                return ResourceManager.GetString("Boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot Sound.
        /// </summary>
        public static string BootSound {
            get {
                return ResourceManager.GetString("BootSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Down.
        /// </summary>
        public static string BrightnessDown {
            get {
                return ResourceManager.GetString("BrightnessDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Up.
        /// </summary>
        public static string BrightnessUp {
            get {
                return ResourceManager.GetString("BrightnessUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black and white tray icon.
        /// </summary>
        public static string BWTrayIcon {
            get {
                return ResourceManager.GetString("BWTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        public static string Calibrate {
            get {
                return ResourceManager.GetString("Calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        public static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Boost.
        /// </summary>
        public static string CPUBoost {
            get {
                return ResourceManager.GetString("CPUBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceleration.
        /// </summary>
        public static string Deceleration {
            get {
                return ResourceManager.GetString("Deceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Controller.
        /// </summary>
        public static string DisableController {
            get {
                return ResourceManager.GetString("DisableController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please disable Windows &gt; Dynamic Lighting.
        /// </summary>
        public static string DisableDynamicLighting {
            get {
                return ResourceManager.GetString("DisableDynamicLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable on lid close.
        /// </summary>
        public static string DisableOnLidClose {
            get {
                return ResourceManager.GetString("DisableOnLidClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable screen overdrive.
        /// </summary>
        public static string DisableOverdrive {
            get {
                return ResourceManager.GetString("DisableOverdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharging.
        /// </summary>
        public static string Discharging {
            get {
                return ResourceManager.GetString("Discharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Color Profiles.
        /// </summary>
        public static string DownloadColorProfiles {
            get {
                return ResourceManager.GetString("DownloadColorProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers and Software.
        /// </summary>
        public static string DriverAndSoftware {
            get {
                return ResourceManager.GetString("DriverAndSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables dGPU to save battery.
        /// </summary>
        public static string EcoGPUTooltip {
            get {
                return ResourceManager.GetString("EcoGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco.
        /// </summary>
        public static string EcoMode {
            get {
                return ResourceManager.GetString("EcoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GPU on shutdown (prevents issue with Eco mode).
        /// </summary>
        public static string EnableGPUOnShutdown {
            get {
                return ResourceManager.GetString("EnableGPUOnShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling the dGPU by going into Eco mode while Display Mode in NVIDIA Control Panel is not set to Optimus might cause problems with brightness controls until after the next reboot. 
        ///
        ///Do you still want to continue?.
        /// </summary>
        public static string EnableOptimusText {
            get {
                return ResourceManager.GetString("EnableOptimusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA Display Mode is not set to Optimus.
        /// </summary>
        public static string EnableOptimusTitle {
            get {
                return ResourceManager.GetString("EnableOptimusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Settings.
        /// </summary>
        public static string EnergySettings {
            get {
                return ResourceManager.GetString("EnergySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Profile.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Settings.
        /// </summary>
        public static string ExtraSettings {
            get {
                return ResourceManager.GetString("ExtraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Defaults.
        /// </summary>
        public static string FactoryDefaults {
            get {
                return ResourceManager.GetString("FactoryDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Curves.
        /// </summary>
        public static string FanCurves {
            get {
                return ResourceManager.GetString("FanCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Fan Profile.
        /// </summary>
        public static string FanProfileCPU {
            get {
                return ResourceManager.GetString("FanProfileCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Fan Profile.
        /// </summary>
        public static string FanProfileGPU {
            get {
                return ResourceManager.GetString("FanProfileGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid Fan Profile.
        /// </summary>
        public static string FanProfileMid {
            get {
                return ResourceManager.GetString("FanProfileMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Profiles.
        /// </summary>
        public static string FanProfiles {
            get {
                return ResourceManager.GetString("FanProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fans and Power.
        /// </summary>
        public static string FansAndPower {
            get {
                return ResourceManager.GetString("FansAndPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fans + Power.
        /// </summary>
        public static string FansPower {
            get {
                return ResourceManager.GetString("FansPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flicker-free Dimming.
        /// </summary>
        public static string FlickerFreeDimming {
            get {
                return ResourceManager.GetString("FlickerFreeDimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Fn+F hotkeys without Fn.
        /// </summary>
        public static string FnLock {
            get {
                return ResourceManager.GetString("FnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FN-Lock Off.
        /// </summary>
        public static string FnLockOff {
            get {
                return ResourceManager.GetString("FnLockOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FN-Lock On.
        /// </summary>
        public static string FnLockOn {
            get {
                return ResourceManager.GetString("FnLockOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Boost.
        /// </summary>
        public static string GPUBoost {
            get {
                return ResourceManager.GetString("GPUBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing.
        /// </summary>
        public static string GPUChanging {
            get {
                return ResourceManager.GetString("GPUChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Clock Offset.
        /// </summary>
        public static string GPUCoreClockOffset {
            get {
                return ResourceManager.GetString("GPUCoreClockOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Clock Offset.
        /// </summary>
        public static string GPUMemoryClockOffset {
            get {
                return ResourceManager.GetString("GPUMemoryClockOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Mode.
        /// </summary>
        public static string GPUMode {
            get {
                return ResourceManager.GetString("GPUMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGPU only.
        /// </summary>
        public static string GPUModeEco {
            get {
                return ResourceManager.GetString("GPUModeEco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGPU + dGPU.
        /// </summary>
        public static string GPUModeStandard {
            get {
                return ResourceManager.GetString("GPUModeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dGPU exclusive.
        /// </summary>
        public static string GPUModeUltimate {
            get {
                return ResourceManager.GetString("GPUModeUltimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Power.
        /// </summary>
        public static string GPUPower {
            get {
                return ResourceManager.GetString("GPUPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Settings.
        /// </summary>
        public static string GPUSettings {
            get {
                return ResourceManager.GetString("GPUSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Target.
        /// </summary>
        public static string GPUTempTarget {
            get {
                return ResourceManager.GetString("GPUTempTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes till Hibernation in sleep on battery (0 - OFF).
        /// </summary>
        public static string HibernateAfter {
            get {
                return ResourceManager.GetString("HibernateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Rotation.
        /// </summary>
        public static string ImageRotation {
            get {
                return ResourceManager.GetString("ImageRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Profile.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval Off.
        /// </summary>
        public static string IntervalOff {
            get {
                return ResourceManager.GetString("IntervalOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval {0}s.
        /// </summary>
        public static string IntervalSeconds {
            get {
                return ResourceManager.GetString("IntervalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Bindings.
        /// </summary>
        public static string KeyBindings {
            get {
                return ResourceManager.GetString("KeyBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all apps using GPU when switching to Eco.
        /// </summary>
        public static string KillGpuApps {
            get {
                return ResourceManager.GetString("KillGpuApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop Backlight.
        /// </summary>
        public static string LaptopBacklight {
            get {
                return ResourceManager.GetString("LaptopBacklight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop Keyboard.
        /// </summary>
        public static string LaptopKeyboard {
            get {
                return ResourceManager.GetString("LaptopKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop Screen.
        /// </summary>
        public static string LaptopScreen {
            get {
                return ResourceManager.GetString("LaptopScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED Status Indicators.
        /// </summary>
        public static string LEDStatusIndicators {
            get {
                return ResourceManager.GetString("LEDStatusIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t check local version.
        /// </summary>
        public static string LegendGray {
            get {
                return ResourceManager.GetString("LegendGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string LegendGreen {
            get {
                return ResourceManager.GetString("LegendGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string LegendRed {
            get {
                return ResourceManager.GetString("LegendRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lid.
        /// </summary>
        public static string Lid {
            get {
                return ResourceManager.GetString("Lid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightbar.
        /// </summary>
        public static string Lightbar {
            get {
                return ResourceManager.GetString("Lightbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        public static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string LockScreen {
            get {
                return ResourceManager.GetString("LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Stick Deadzones.
        /// </summary>
        public static string LSDeadzones {
            get {
                return ResourceManager.GetString("LSDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Trigger Deadzones.
        /// </summary>
        public static string LTDeadzones {
            get {
                return ResourceManager.GetString("LTDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Visualizer.
        /// </summary>
        public static string MatrixAudio {
            get {
                return ResourceManager.GetString("MatrixAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Banner.
        /// </summary>
        public static string MatrixBanner {
            get {
                return ResourceManager.GetString("MatrixBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright.
        /// </summary>
        public static string MatrixBright {
            get {
                return ResourceManager.GetString("MatrixBright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string MatrixClock {
            get {
                return ResourceManager.GetString("MatrixClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.
        /// </summary>
        public static string MatrixDim {
            get {
                return ResourceManager.GetString("MatrixDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rog Logo.
        /// </summary>
        public static string MatrixLogo {
            get {
                return ResourceManager.GetString("MatrixLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MatrixMedium {
            get {
                return ResourceManager.GetString("MatrixMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string MatrixOff {
            get {
                return ResourceManager.GetString("MatrixOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string MatrixPicture {
            get {
                return ResourceManager.GetString("MatrixPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max refresh rate for lower latency.
        /// </summary>
        public static string MaxRefreshTooltip {
            get {
                return ResourceManager.GetString("MaxRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60Hz refresh rate to save battery.
        /// </summary>
        public static string MinRefreshTooltip {
            get {
                return ResourceManager.GetString("MinRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Snapping.
        /// </summary>
        public static string MouseAngleSnapping {
            get {
                return ResourceManager.GetString("MouseAngleSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Power Off After.
        /// </summary>
        public static string MouseAutoPowerOff {
            get {
                return ResourceManager.GetString("MouseAutoPowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Response.
        /// </summary>
        public static string MouseButtonResponse {
            get {
                return ResourceManager.GetString("MouseButtonResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed. Selected file is not a valid mouse profile or corrutpted..
        /// </summary>
        public static string MouseImportFailed {
            get {
                return ResourceManager.GetString("MouseImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift Off Distance.
        /// </summary>
        public static string MouseLiftOffDistance {
            get {
                return ResourceManager.GetString("MouseLiftOffDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Battery Warning at.
        /// </summary>
        public static string MouseLowBatteryWarning {
            get {
                return ResourceManager.GetString("MouseLowBatteryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string MousePerformance {
            get {
                return ResourceManager.GetString("MousePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize with mouse.
        /// </summary>
        public static string MouseSynchronize {
            get {
                return ResourceManager.GetString("MouseSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Zone.
        /// </summary>
        public static string Multizone {
            get {
                return ResourceManager.GetString("Multizone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Zone Strong.
        /// </summary>
        public static string MultizoneStrong {
            get {
                return ResourceManager.GetString("MultizoneStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        public static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Mic.
        /// </summary>
        public static string MuteMic {
            get {
                return ResourceManager.GetString("MuteMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New updates.
        /// </summary>
        public static string NewUpdates {
            get {
                return ResourceManager.GetString("NewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates.
        /// </summary>
        public static string NoNewUpdates {
            get {
                return ResourceManager.GetString("NoNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Zone.
        /// </summary>
        public static string OneZone {
            get {
                return ResourceManager.GetString("OneZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open G-Helper window.
        /// </summary>
        public static string OpenGHelper {
            get {
                return ResourceManager.GetString("OpenGHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized.
        /// </summary>
        public static string Optimized {
            get {
                return ResourceManager.GetString("Optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Eco on battery and to Standard when plugged in.
        /// </summary>
        public static string OptimizedGPUTooltip {
            get {
                return ResourceManager.GetString("OptimizedGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep GPU disabled on USB-C charger in Optimized mode.
        /// </summary>
        public static string OptimizedUSBC {
            get {
                return ResourceManager.GetString("OptimizedUSBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdrive.
        /// </summary>
        public static string Overdrive {
            get {
                return ResourceManager.GetString("Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string PerformanceMode {
            get {
                return ResourceManager.GetString("PerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripherals.
        /// </summary>
        public static string Peripherals {
            get {
                return ResourceManager.GetString("Peripherals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture / Gif.
        /// </summary>
        public static string PictureGif {
            get {
                return ResourceManager.GetString("PictureGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Pause.
        /// </summary>
        public static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Rate.
        /// </summary>
        public static string PollingRate {
            get {
                return ResourceManager.GetString("PollingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Limits.
        /// </summary>
        public static string PowerLimits {
            get {
                return ResourceManager.GetString("PowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Limits is an experimental feature. Use carefully and at your own risk!.
        /// </summary>
        public static string PPTExperimental {
            get {
                return ResourceManager.GetString("PPTExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintScreen.
        /// </summary>
        public static string PrintScreen {
            get {
                return ResourceManager.GetString("PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is using dGPU and preventing Eco mode. Let G-Helper try to restart dGPU in device manager? (Please proceed at your own risk).
        /// </summary>
        public static string RestartGPU {
            get {
                return ResourceManager.GetString("RestartGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        public static string RPM {
            get {
                return ResourceManager.GetString("RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Stick Deadzones.
        /// </summary>
        public static string RSDeadzones {
            get {
                return ResourceManager.GetString("RSDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Trigger Deadzones.
        /// </summary>
        public static string RTDeadzones {
            get {
                return ResourceManager.GetString("RTDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on Startup.
        /// </summary>
        public static string RunOnStartup {
            get {
                return ResourceManager.GetString("RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling Quality.
        /// </summary>
        public static string ScalingQuality {
            get {
                return ResourceManager.GetString("ScalingQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenpad Brightness Down.
        /// </summary>
        public static string ScreenPadDown {
            get {
                return ResourceManager.GetString("ScreenPadDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenpad Brightness Up.
        /// </summary>
        public static string ScreenPadUp {
            get {
                return ResourceManager.GetString("ScreenPadUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent.
        /// </summary>
        public static string Silent {
            get {
                return ResourceManager.GetString("Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Level.
        /// </summary>
        public static string SlashBatteryLevel {
            get {
                return ResourceManager.GetString("SlashBatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Stream.
        /// </summary>
        public static string SlashBitStream {
            get {
                return ResourceManager.GetString("SlashBitStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounce.
        /// </summary>
        public static string SlashBounce {
            get {
                return ResourceManager.GetString("SlashBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer.
        /// </summary>
        public static string SlashBuzzer {
            get {
                return ResourceManager.GetString("SlashBuzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string SlashFlow {
            get {
                return ResourceManager.GetString("SlashFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux.
        /// </summary>
        public static string SlashFlux {
            get {
                return ResourceManager.GetString("SlashFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        public static string SlashGameOver {
            get {
                return ResourceManager.GetString("SlashGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard.
        /// </summary>
        public static string SlashHazard {
            get {
                return ResourceManager.GetString("SlashHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfacing.
        /// </summary>
        public static string SlashInterfacing {
            get {
                return ResourceManager.GetString("SlashInterfacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string SlashLoading {
            get {
                return ResourceManager.GetString("SlashLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slash.
        /// </summary>
        public static string SlashMode {
            get {
                return ResourceManager.GetString("SlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phantom.
        /// </summary>
        public static string SlashPhantom {
            get {
                return ResourceManager.GetString("SlashPhantom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp.
        /// </summary>
        public static string SlashRamp {
            get {
                return ResourceManager.GetString("SlashRamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum.
        /// </summary>
        public static string SlashSpectrum {
            get {
                return ResourceManager.GetString("SlashSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string SlashStart {
            get {
                return ResourceManager.GetString("SlashStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string SlashStatic {
            get {
                return ResourceManager.GetString("SlashStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string SlashTransmission {
            get {
                return ResourceManager.GetString("SlashTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables dGPU for standard use.
        /// </summary>
        public static string StandardGPUTooltip {
            get {
                return ResourceManager.GetString("StandardGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string StandardMode {
            get {
                return ResourceManager.GetString("StandardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Services.
        /// </summary>
        public static string StartingServices {
            get {
                return ResourceManager.GetString("StartingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        public static string StartupError {
            get {
                return ResourceManager.GetString("StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop GPU Applications.
        /// </summary>
        public static string StopGPUApps {
            get {
                return ResourceManager.GetString("StopGPUApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Services.
        /// </summary>
        public static string StoppingServices {
            get {
                return ResourceManager.GetString("StoppingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Aura.
        /// </summary>
        public static string ToggleAura {
            get {
                return ResourceManager.GetString("ToggleAura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Toggle Clamshell Mode.
        /// </summary>
        public static string ToggleClamshellMode {
            get {
                return ResourceManager.GetString("ToggleClamshellMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Fn-Lock.
        /// </summary>
        public static string ToggleFnLock {
            get {
                return ResourceManager.GetString("ToggleFnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Miniled (if supported).
        /// </summary>
        public static string ToggleMiniled {
            get {
                return ResourceManager.GetString("ToggleMiniled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Screen.
        /// </summary>
        public static string ToggleScreen {
            get {
                return ResourceManager.GetString("ToggleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Touchscreen.
        /// </summary>
        public static string ToggleTouchscreen {
            get {
                return ResourceManager.GetString("ToggleTouchscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchscreen.
        /// </summary>
        public static string Touchscreen {
            get {
                return ResourceManager.GetString("Touchscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbo.
        /// </summary>
        public static string Turbo {
            get {
                return ResourceManager.GetString("Turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned off.
        /// </summary>
        public static string TurnedOff {
            get {
                return ResourceManager.GetString("TurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable on battery.
        /// </summary>
        public static string TurnOffOnBattery {
            get {
                return ResourceManager.GetString("TurnOffOnBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes laptop screen to dGPU, maximizing FPS.
        /// </summary>
        public static string UltimateGPUTooltip {
            get {
                return ResourceManager.GetString("UltimateGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate.
        /// </summary>
        public static string UltimateMode {
            get {
                return ResourceManager.GetString("UltimateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undervolting is an experimental and risky feature. If applied values are too low for your hardware, it can become unstable, shut down or cause data corruption. If you want to try - start from small values first, click Apply and test what works for you..
        /// </summary>
        public static string UndervoltingRisky {
            get {
                return ResourceManager.GetString("UndervoltingRisky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmuted.
        /// </summary>
        public static string Unmuted {
            get {
                return ResourceManager.GetString("Unmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration Strength.
        /// </summary>
        public static string VibrationStrength {
            get {
                return ResourceManager.GetString("VibrationStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Mode.
        /// </summary>
        public static string VisualMode {
            get {
                return ResourceManager.GetString("VisualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Modes are not available when HDR is active.
        /// </summary>
        public static string VisualModesHDR {
            get {
                return ResourceManager.GetString("VisualModesHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Modes are not available when laptop screen is off.
        /// </summary>
        public static string VisualModesScreen {
            get {
                return ResourceManager.GetString("VisualModesScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Down.
        /// </summary>
        public static string VolumeDown {
            get {
                return ResourceManager.GetString("VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mute.
        /// </summary>
        public static string VolumeMute {
            get {
                return ResourceManager.GetString("VolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        public static string VolumeUp {
            get {
                return ResourceManager.GetString("VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep app window always on top.
        /// </summary>
        public static string WindowTop {
            get {
                return ResourceManager.GetString("WindowTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
